# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# command_timeout = 2000

# Inserts a blank line between shell prompts
add_newline = false

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$deno\
$golang\
$helm\
$java\
$kotlin\
$lua\
$nodejs\
$python\
$ruby\
$rust\
$scala\
$terraform\
$container\
$docker_context\
$kubernetes\
$fill\
$status\
$aws\
$gcloud\
$azure\
$direnv\
$env_var\
$mise\
$sudo\
$cmd_duration\
$time\
$line_break\
$character\
"""


# $package\
# $c\
# $cmake\
# $cobol\
# $daml\
# $dart\
# $deno\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $fennel\
# $gleam\
# $golang\
# $guix_shell\
# $haskell\
# $haxe\
# $helm\
# $java\
# $julia\
# $kotlin\
# $gradle\
# $lua\
# $nim\
# $nodejs\
# $ocaml\
# $opa\
# $perl\
# $php\
# $pulumi\
# $purescript\
# $python\
# $quarto\
# $raku\
# $rlang\
# $red\
# $ruby\
# $rust\
# $scala\
# $solidity\
# $swift\
# $terraform\
# $typst\
# $vlang\
# $vagrant\
# $zig\
# $buf\
# $nix_shell\
# $conda\
# $meson\
# $spack\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $azure\
# $nats\
# $direnv\
# $env_var\
# $mise\
# $crystal\
# $custom\
# $sudo\
# $cmd_duration\
# $line_break\
# $jobs\
# $battery\

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.gruvbox_dark]
color_ok = '#b8bb26'
color_danger = '#fb4934'
color_caution = '#d79921'
color_os = '#d65d0e'
color_username = '#d65d0e'
color_directory = '#d79921'
color_git = '#689d6a'
color_git_added = '#b8bb26'
color_git_deleted = '#fb4934'
color_env = '#458588'
color_kubernetes = '#b16286'
color_docker = '#458588'
color_shell = '#a89984'
color_container = '#cc241d'
color_other = '#d5c4a1'
color_time = '#fbf1c7'
color_duration = '#fbf1c7'
color_vimcmd_ok = '#8ec07c'
color_vimcmd_replace = '#b16286'
color_vimcmd_visual = '#d79921'

[os]
disabled = false
style = "fg:text"
format = '[$symbol]($style)'

[os.symbols]
Macos = "Û∞Äµ"

[username]
show_always = true
style_user = "fg:green"
style_root = "bold fg:red"
format = '[ $user ]($style)'

[directory]
style = "fg:blue"
read_only_style = "fg:flamingo"
repo_root_style = "bold fg:blue"
format = "[$path ]($style)"
read_only = "ÔÄ£"
home_symbol = "~"
truncation_symbol = "‚Ä¶/"
truncation_length = 2
truncate_to_repo = false
fish_style_pwd_dir_length = 0
use_logical_path = true

[git_branch]
symbol = "Óú•"
style = "fg:green"
format = '([$symbol $branch]($style) )'
only_attached = true
ignore_branches = []
truncation_length = 25
truncation_symbol = "..."
always_show_remote = false
disabled = false

[git_commit]
style = "fg:green"
format = "([($tag)(@$hash)]($style) )"
commit_hash_length = 7
only_detached = true
tag_symbol = "Û∞ìº "
tag_disabled = false
disabled = false

[git_status]
style = "fg:green"
format = '([$ahead_behind]($style) )([$all_status]($style) )'
stashed = "*${count}"
ahead = "[‚á°($count)](green)"
behind = "[‚á£($count)](maroon)"
up_to_date = ""
diverged = "[‚á°($ahead_count)](green)[‚á£($behind_count)](maroon)"
conflicted = "[c($count) ](red)"
deleted = "[√ó($count) ](maroon)"
renamed = "¬ª${count}"
modified = "[!($count) ](peach)"
staged = "[+($count) ](green)"
untracked = "[?($count)](red)"
ignore_submodules = false
disabled = false

[git_metrics]
format = '([([+$added]($added_style))([-$deleted]($deleted_style))](fg:color_git) )'
added_style = "fg:yellow"
deleted_style = "fg:red"
only_nonzero_diffs = true
disabled = true

[git_state]
style = "fg:red"
format = '([$state( $progress_current/$progress_total)]($style bold) )'
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
disabled = false

[nodejs]
symbol = "Ó¥ç"
style = "fg:green"
format = '([$symbol( $version)]($style) )'

# [c]
# symbol = "Óòû"
# style = "fg:color_env"
# format = '( [$symbol( $version)]($style) )'

[rust]
symbol = "Û±òó"
style = "fg:flamingo"
format = '([$symbol( $version)]($style) )'

[golang]
symbol = "Óòß"
style = "fg:sapphire"
format = '([$symbol( $version)]($style) )'

# [php]
# symbol = "Óòà"
# style = "fg:color_env"
# format = '( [$symbol( $version)]($style) )'

[java]
symbol = "Óâñ"
style = "fg:peach"
format = '([$symbol( $version)]($style) )'

[kotlin]
symbol = "Óò¥"
style = "fg:peach"
format = '([$symbol( $version)]($style) )'

[lua]
symbol = "Óò†"
style = "fg:blue"
format = 'via [$symbol( $version)]($style) '

[ruby]
symbol = "Óúπ"
style = "fg:red"
format = '([$symbol( $version)]($style) )'

# [haskell]
# symbol = "Óòü"
# style = "fg:color_env"
# format = '( [$symbol( $version)]($style) )'

[python]
symbol = "ÓòÜ"
style = "fg:yellow"
format = '([$symbol( $version)( $virtualenv)]($style) )'
version_format = '${raw}'

[package]
disabled = false
symbol = "Û∞èó"
style = "fg:rosewater"
format = '([$symbol( $version)]($style) )'

[docker_context]
symbol = "Ôåà"
style = "fg:sapphire"
format = '([$symbol( $context)]($style) )'

[kubernetes]
symbol = "Û±Éæ"
style = "fg:blue"
format = '([($symbol( $cluster))]($style) )'
disabled = false

# [shell]
# disabled = false
# format = '[ ÓØä $indicator ]($style)'
# bash_indicator = "bash"
# fish_indicator = "fish"
# zsh_indicator = "zsh"
# powershell_indicator = "powershell"
# pwsh_indicator = "pwsh"
# ion_indicator = "ion"
# elvish_indicator = "elvish"
# tcsh_indicator = "tcsh"
# xonsh_indicator = "xonsh"
# cmd_indicator = "cmd"
# nu_indicator = "nu"
# unknown_indicator = ""
# style = "fg:color_shell"

[container]
style = "fg:red"
format = '([$symbol $name]($style) )'

# [jobs]
# symbol = "Û∞íã"
# style = "fg:color_other"
# format = '( [$symbol( $number)]($style) )'
# symbol_threshold = 1
# number_threshold = 1
#
# [custom.memory_usage]
# command = "starship module memory_usage"
# when = '[ "${STARSHIP_COCKPIT_MEMORY_USAGE_ENABLED:-false}" = "true" ]'
# shell = "sh"
# format = "( $output )"
# disabled = false
#
# [memory_usage]
# threshold = 0
# symbol = "Û∞ìÖ"
# style = "fg:color_other"
# format = '( [$symbol( ${ram})]($style) )'
# disabled = false
#
# [custom.battery]
# command = """
# battery_info=$(starship module battery)
# if [ -n "$battery_info" ]; then
#     percent=$(echo "$battery_info" | grep -o '[0-9]*%' | sed 's/%//')
#     if [ "$percent" -le "${STARSHIP_COCKPIT_BATTERY_THRESHOLD:-0}" ]; then
#         echo "$battery_info" | sed 's/%%/%/'
#     fi
# fi
# """
# when = '[ "${STARSHIP_COCKPIT_BATTERY_ENABLED:-false}" = "true" ]'
# shell = "sh"
# format = "( $output )"
# disabled = false
#
# [battery]
# full_symbol = "Û∞Åπ"
# charging_symbol = "Û∞ÇÑ"
# discharging_symbol = "Û∞ÇÉ"
# unknown_symbol = "Û∞Çë"
# empty_symbol = "Û∞Çé"
# format = '( [$symbol( $percentage)]($style) )'
# disabled = false
#
# [[battery.display]]
# threshold = 10
# style = "bold fg:color_danger"
#
# [[battery.display]]
# threshold = 20
# style = "fg:color_caution"
#
# [[battery.display]]
# threshold = 100
# style = "fg:color_other"

[time]
#  üïô ÔÜò  Ôâ®  Ó∏®  Ôáê  ÔÄó  Ó∫®  Óäé  ÓµÜ  Ó∫ô |
format = '[ÔÄó ](bold text)[$time]($style) '
style = 'fg:text bold'
time_format = '%I:%M%P'
use_12hr = true
disabled = false

[fill]
symbol = ' '
disabled = false

[cmd_duration]
min_time = 5000
format = '( [Û±´ë $duration]($style) )'
style = 'fg:rosewater'
show_milliseconds = false
disabled = false

[status]
disabled = false
format = '( [$symbol( $common_meaning)( $signal_name)]($style) )'
map_symbol = true
pipestatus = true
symbol = 'Û∞Öô'
success_symbol = ''
not_executable_symbol = 'Û∞Ç≠'
not_found_symbol = 'Û∞çâ'
sigint_symbol = 'Û∞êä'
signal_symbol = 'Û±êã'
style = 'bold fg:red'
recognize_signal_code = true

[line_break]
disabled = false

[character]
disabled = false
format = '$symbol '
success_symbol = '[‚ùØ](bold fg:green)'
error_symbol = '[‚ùØ](bold fg:red)'
vimcmd_symbol = '[ÓüÖ](bold fg:green)'
vimcmd_replace_one_symbol = '[ÓüÖ](bold fg:maroon)'
vimcmd_replace_symbol = '[ÓüÖ](bold fg:maroon)'
vimcmd_visual_symbol = '[ÓüÖ](bold fg:blue)'

# [custom.keyboard_layout]
# command = """
#
# # Set env variables if you want to use layout aliases (in uppercase)
# #     export STARSHIP_COCKPIT_KEYBOARD_LAYOUT_ABC=ENG
# #     export STARSHIP_COCKPIT_KEYBOARD_LAYOUT_UKRAINIAN=UKR
# #
# # Implementations:
# #     macOS
#
# if [ "$(uname -s)" = "Darwin" ]; then
#         input_source=$(defaults read ~/Library/Preferences/com.apple.HIToolbox.plist AppleCurrentKeyboardLayoutInputSourceID)
#         layout_id=$(echo "$input_source" | cut -d '.' -f4)
#         layout=$(printenv "STARSHIP_COCKPIT_KEYBOARD_LAYOUT_$(echo "$layout_id" | tr '[:lower:]' '[:upper:]')")
#         echo "$layout" || echo "$layout_id"
# fi

# """
# symbol = "Û∞åå"
# style = "fg:color_other"
# format = '( [$symbol $output]($style) )'
# when = '[ "${STARSHIP_COCKPIT_KEYBOARD_LAYOUT_ENABLED:-false}" = "true" ]'
# shell = "sh"
# disabled = false
